### ISSUE TITLE
27 CFR 478 Verification

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#103]
* [x] 03-1657 2003 Annual (#127 , 18f/fr-notices#6)
* [x] E8-23178 Final Rule (18f/fr-notices#7)
* [x] E9-527 2009 Annual
* [x] 2010-13392 2011 Annual
* [x] 2012-13762 Final Rule (18f/regulations-parser#140, 18f/regulations-parser#141, 18f/fr-notices#11)
* [x] 2012-13770 2013 Annual
* [x] 2014-18842 Final Rule (18f/fr-notices#12)
* [x] 2014-18392 2015 Annual

**Comment by cmc333333** [comment]
Bringing this into the previous sprint as we have a bit more capacity than we planned for. Will split into sub issues where appropriate.

**Comment by cmc333333** [comment]
Everything merged!
