### ISSUE TITLE
555 Verification

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#37]
* [x] 03-1657 - Ignored; 03-6573 is the beginning of time
* [x] 03-6573 - Annual edition, 2003 #101
* [x] 03-23093 - Annual edition, 2004 18f/fr-notices#8
* [x] 05-10618 - Annual edition, 2006 (though see #120)
* [x] 06-6862 - Annual edition, 2007 #121
* [x] E8-23178 - Notice must be parsed
* [x] E9-578 - Annual edition, 2009
* [x] 2010-891 - Annual edition, 2010
* [x] 2014-18842 - Annual edition, 2015
* [x] 2015-25190 - Notice must be parsed 18f/fr-notices#10

**Comment by cmc333333** [comment]
### 03-23093
* Something's wrong with the table in 218
* Something's wrong with the table in 220
* Something's wrong with the table in 223

### 05-10618
* Something's wrong with the table in 218
* Something's wrong with the table in 220
* Something's wrong with the table in 223

### 06-6862
* TOC indicates something's changed in 78, but I can't see what
* Something's wrong with the table in 222
* Something's wrong with the table in 224

### E8-23178
* Not verified -- diff didn't exist

### E9-578
* A few of E8-23178's changes are applied here
* Weird diff in 127, I think related to a space being present between two section markers
* Something's wrong with the table in 220

### 2014-18842
* Definition of "Customs Officer" claims to have changed in the rule, but I'm not seeing a diff in eregs
* Reordering the definitions creates some diff havok
* Typographical change in 180 may be incorrect
* Something's wrong with the table in 220
* Something's wrong with the table in 222
* Something's wrong with the table in 224

### 2015-25190
* Diff does not exist

**Comment by cmc333333** [comment]
@tadhg-ohiggins here's the meta issue around 555 diff tracking

**Comment by tadhg-ohiggins** [comment]
All known problems addressed, and I went through the original, and each diff since then and found that it matched the FR changes. Closing.
